- name: restart as sudo
  hosts: isu_g1
  become: yes # sudo で実行する
  tasks:
  - ansible.builtin.shell:
      cmd: /opt/isucon-env-checker/envcheck
  - ansible.builtin.systemd_service:
      state: stopped
      name: isuride-go
  # nginx
  - ansible.builtin.systemd_service:
      state: stopped
      name: nginx
  - ansible.builtin.shell:
      cmd: rm -f /var/log/nginx/access.log
  - ansible.builtin.systemd_service:
      state: started
      name: nginx
  - ansible.builtin.systemd_service:
      state: started
      name: isuride-go
- name: restart as sudo
  hosts: isu_g2
  become: yes # sudo で実行する
  tasks:
  - ansible.builtin.shell:
      cmd: /opt/isucon-env-checker/envcheck
  # mysql
  - ansible.builtin.systemd_service:
      state: stopped
      name: mysql
  - ansible.builtin.shell:
      cmd: rm -f /var/log/mysql/mysql-slow.log
  - ansible.builtin.systemd_service:
      state: started
      name: mysql
