- name: deploy
  hosts: isu_g1
  tasks:
  # - name: Ping my hosts
  #   ansible.builtin.ping:
  # - name: Print message
  #   ansible.builtin.debug:
  #     msg: Hello world
  # - ansible.builtin.copy:
  #     force: true
  #     src: ./webapp/
  #     dest: /tmp/webapp/
  # - ansible.builtin.shell:
  #     cmd: mv /tmp/webapp/ ~/webapp/
  - name: copy app
    # ansible.builtin.copy は遅いので synchronize 使う
    ansible.builtin.synchronize:
      src: ./webapp/
      dest: ~/webapp/
- name: deploy as sudo
  hosts: isu_g1
  become: yes # sudo で実行する
  tasks:
  - ansible.builtin.synchronize:
      src: ./systemd/system/isuports.service
      dest: /etc/systemd/system/isuports.service
  - ansible.builtin.synchronize:
      src: ./etc/mysql/mysql.conf.d/mysqld.conf
      dest: /etc/mysql/mysql.conf.d/mysqld.conf
- name: restart as sudo
  hosts: isu_g1
  become: yes # sudo で実行する
  tasks:
  - name: restart app
    ansible.builtin.systemd_service:
      state: restarted
      name: isuports
  - name: restart nginx
    ansible.builtin.systemd_service:
      state: restarted
      name: nginx
  - name: restart mysql
    ansible.builtin.systemd_service:
      state: restarted
      name: mysql
