- name: deploy app
  hosts: isu_a
  become_user: isucon # isuconユーザーとして実行する
  tasks:
   # - name: Ping my hosts
   #   ansible.builtin.ping:
   # - name: Print message
   #   ansible.builtin.debug:
   #     msg: Hello world
   # - ansible.builtin.copy:
   #     force: true
   #     src: ./webapp/
   #     dest: /tmp/webapp/
   # - ansible.builtin.shell:
   #     cmd: mv /tmp/webapp/ ~/webapp/
   - name: copy app
     ansible.builtin.synchronize:
       src: ./webapp/
       dest: ~/webapp/
- name: deploy systemd
  hosts: isu_a
- name: restart
  hosts: isu_a
  become: yes # sudo で実行する
  tasks:
   - name: restart app
     ansible.builtin.systemd_service:
       state: restarted
       name: isuports
